apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-argocd-k8s-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/achavanga/springboot-argocd-k8s.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: springboot-argocd-k8s-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true