apiVersion: v1
kind: Service
metadata:
  name: springboot-argocd-k8s-app
spec:
  selector:
    app: springboot-argocd-k8s-app
  ports:
    - protocol: "TCP"
      port: 9080
      targetPort: 9080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-argocd-k8s-app
spec:
  selector:
    matchLabels:
      app: springboot-argocd-k8s-app
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-argocd-k8s-app
    spec:
      containers:
        - name: springboot-argocd-k8s-app
          image: ghcr.io/achavanga/springdemo/springboot-argocd-k8s-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9080